name: faiadashu
description: Faiadashu FHIRDash - Build beautiful healthcare apps fast — use the Flutter™ SDK and follow the HL7® FHIR® standard.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.6.0-dev.3
homepage: https://tiloc.github.io/faiadashu/
repository: https://github.com/tiloc/faiadashu
issue_tracker: https://github.com/tiloc/faiadashu/issues

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  collection: ^1.15.0
#  fhir: ^0.5.0-11
#  fhir_path: ^0.5.0-17
  fhir:
    path: /Users/tilo/Projects/fhir/fhir
  fhir_path:
    path: /Users/tilo/Projects/fhir/fhir_path
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  logging: ^1.0.2
  markdown: ^4.0.1
  meta: ^1.7.0
  scrollable_positioned_list: ^0.2.3
  simple_html_css: ^3.0.1
  webview_flutter: ^3.0.0
  webview_flutter_web: ^0.1.0

dev_dependencies:
  dart_code_metrics: ^4.1.0

  flutter_test:
    sdk: flutter

  lint: ^1.8.1

dependency_overrides:
  fhir:
    path: /Users/tilo/Projects/fhir/fhir


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
