name: faiabench
description: The Faiabench FHIRÂ® SDC IG workbench

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  code_text_field: ^1.0.2

  collection: ^1.15.0

  faiadashu:
    path: ..

  fhir: ^0.5.0-10

#  fhir_path: ^0.5.0-16
  fhir_path:
    path: ../../fhir/fhir_path

  flutter:
    sdk: flutter

  flutter_highlight: ^0.7.0

  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^1.0.1

  highlight: ^0.7.0

  intl: ^0.17.0

  logging: ^1.0.1

  multi_split_view: ^1.10.0+1

  simple_html_css: ^3.0.1



dev_dependencies:
  lint: ^1.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/initial/
