name: faiadashu_online
description: Faiadashu Online - Functionalities for faiadashu that connect to FHIR(R) servers.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: none

version: 0.6.0-dev.5
homepage: https://tiloc.github.io/faiadashu/
repository: https://github.com/tiloc/faiadashu
issue_tracker: https://github.com/tiloc/faiadashu/issues

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  faiadashu:
    path: ..

  fhir: ^0.8.0

  fhir_at_rest: ^0.8.3

  fhir_auth: ^0.8.0
#  fhir_auth:
#    path: ../../fhir/fhir_auth

  flutter:
    sdk: flutter
  logging: ^1.0.2

  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.8.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
